// <auto-generated />
using Doodle_Forms.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Doodle_Forms.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250101030925_AddUserPrimaryKey")]
    partial class AddUserPrimaryKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Doodle_Forms.Migrations.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("Doodle_Forms.Migrations.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MultipleStringsQuestion1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("MultipleStringsQuestion1State")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MultipleStringsQuestion2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("MultipleStringsQuestion2State")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MultipleStringsQuestion3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("MultipleStringsQuestion3State")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MultipleStringsQuestion4")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("MultipleStringsQuestion4State")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SingleStringQuestion1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("SingleStringQuestion1State")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SingleStringQuestion2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("SingleStringQuestion2State")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SingleStringQuestion3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("SingleStringQuestion3State")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SingleStringQuestion4")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("SingleStringQuestion4State")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("Doodle_Forms.Migrations.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
